In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import MinMaxScaler

#**Loading Files**

In [ ]:
df1 = pd.read_csv('Social_Network_Ads.csv')

In [ ]:
df2 = pd.read_csv('student3.csv')
df2

    roll     name class  marks    age
0      1     anil    TE   56.77  22.0
1      2     amit    TE   59.77  21.0
2      3   aniket    BE   76.88  19.0
3      4  ajinkya    TE   69.66  20.0
4      5     asha    TE   63.28   NaN
5      6   ayesha    BE     NaN  20.0
6      7     amar    BE   65.34  19.0
7      8    Amita    be   68.33  23.0
8      9     amol    TE   56.75  20.0
9      9     amol    TE   56.75  20.0
10    10    anmol    BE   78.66   NaN
11    11   surbhi    TE     NaN  23.0
12    12    Sujay    TE   74.12  22.0
13    13  subhash    be   88.45  21.0
14    14   sachin   NaN   59.33  21.0
15    15  shalini    TE   63.45  20.0

#**Merging wo files**

In [ ]:
merged = pd.merge(df1, df2, on='age')
merged

,User ID,Gender,age,EstimatedSalary,Purchased,roll,name,class,marks
0,15624510,Male,19,19000,0,3,aniket,BE,76.88
1,15624510,Male,19,19000,0,7,amar,BE,65.34
2,15804002,Male,19,76000,0,3,aniket,BE,76.88
3,15804002,Male,19,76000,0,7,amar,BE,65.34
4,15672091,Female,19,21000,0,3,aniket,BE,76.88
...,...,...,...,...,...,...,...,...,...
78,15774179,Female,22,27000,0,12,Sujay,TE,74.12
79,15684801,Male,22,81000,0,1,anil,TE,56.77
80,15684801,Male,22,81000,0,12,Sujay,TE,74.12
81,15762228,Female,22,55000,0,1,anil,TE,56.77
82,15762228,Female,22,55000,0,12,Sujay,TE,74.12

#**Filtering merged file**

In [ ]:
merged.filter(["User ID"])

     User ID
0   15624510
1   15624510
2   15804002
3   15804002
4   15672091
..       ...
78  15774179
79  15684801
80  15684801
81  15762228
82  15762228

[83 rows x 1 columns]

#**Sampling**

In [ ]:
merged.sample(frac = .1)

,User ID,Gender,age,EstimatedSalary,Purchased,roll,name,class,marks
4,15672091,Female,19,21000,0,3,aniket,BE,76.88
24,15709476,Male,20,49000,0,4,ajinkya,TE,69.66
8,15807909,Male,19,85000,0,3,aniket,BE,76.88
27,15709476,Male,20,49000,0,9,amol,TE,56.75
57,15638963,Female,21,68000,0,14,sachin,NaN,59.33
37,15767871,Male,20,74000,0,9,amol,TE,56.75
19,15595228,Female,20,23000,0,4,ajinkya,TE,69.66
3,15804002,Male,19,76000,0,7,amar,BE,65.34

#**Data Inspection**

In [ ]:
df1.head()
df1.info()
df1.describe()
df1.isnull()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   User ID          400 non-null    int64
 1   Gender           400 non-null    object
 2   age              400 non-null    int64
 3   EstimatedSalary  400 non-null    int64
 4   Purchased        400 non-null    int64
dtypes: int64(4), object(1)
memory usage: 15.8+ KB

     User ID  Gender    age  EstimatedSalary  Purchased
0      False   False  False            False      False
1      False   False  False            False      False
2      False   False  False            False      False
3      False   False  False            False      False
4      False   False  False            False      False
..       ...     ...    ...              ...        ...
395    False   False  False            False      False
396    False   False  False            False      False
397    False   False  False            False      False
398    False   False  False            False      False
399    False   False  False            False      False

[400 rows x 5 columns]

#**Drop null values**

In [ ]:
df1.dropna()

      User ID  Gender  age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

#**Handeling missing values**

In [ ]:
df2['marks '].fillna(df2['marks '].mean())

0     56.770000
1     59.770000
2     76.880000
3     69.660000
4     63.280000
5     66.967143
6     65.340000
7     68.330000
8     56.750000
9     56.750000
10    78.660000
11    66.967143
12    74.120000
13    88.450000
14    59.330000
15    63.450000
Name: marks , dtype: float64

In [ ]:
df2['age'].fillna(df2['age'].mode()[0])

0     22.0
1     21.0
2     19.0
3     20.0
4     20.0
5     20.0
6     19.0
7     23.0
8     20.0
9     20.0
10    20.0
11    23.0
12    22.0
13    21.0
14    21.0
15    20.0
Name: age, dtype: float64

#**Data Transformation**

In [ ]:
df1 = pd.read_csv('Social_Network_Ads.csv')
x = df1[['age','EstimatedSalary']]
scaler = MinMaxScaler()
x_scaled = scaler.fit_transform(x)
x_scaled

array([[0.02380952, 0.02962963],
       [0.4047619 , 0.03703704],
       [0.19047619, 0.20740741],
       [0.21428571, 0.31111111],
       [0.02380952, 0.45185185],
       [0.21428571, 0.31851852],
       [0.21428571, 0.51111111],
       [0.33333333, 1.        ],
       [0.16666667, 0.13333333],
       [0.4047619 , 0.37037037],
       [0.19047619, 0.48148148],
       [0.19047619, 0.27407407],
       [0.04761905, 0.52592593],
       [0.33333333, 0.02222222],
       [0.        , 0.4962963 ],
       [0.26190476, 0.48148148],
       [0.69047619, 0.07407407],
       [0.64285714, 0.08148148],
       [0.66666667, 0.0962963 ],
       [0.71428571, 0.1037037 ],
       [0.64285714, 0.05185185],
       [0.69047619, 0.25185185],
       [0.71428571, 0.19259259],
       [0.64285714, 0.05185185],
       [0.66666667, 0.05925926],
       [0.69047619, 0.03703704],
       [0.73809524, 0.0962963 ],
       [0.69047619, 0.11111111],
       [0.26190476, 0.20740741],
       [0.30952381, 0.02222222],
       [0.30952381, 0.43703704],
       [0.21428571, 0.9037037 ],
       [0.07142857, 0.00740741],
       [0.23809524, 0.21481481],
       [0.21428571, 0.55555556],
       [0.4047619 , 0.08888889],
       [0.35714286, 0.0962963 ],
       [0.28571429, 0.25185185],
       [0.19047619, 0.42222222],
       [0.21428571, 0.11851852],
       [0.21428571, 0.01481481],
       [0.35714286, 0.26666667],
       [0.4047619 , 0.68888889],
       [0.28571429, 0.        ],
       [0.23809524, 0.51111111],
       [0.11904762, 0.03703704],
       [0.16666667, 0.47407407],
       [0.21428571, 0.28888889],
       [0.28571429, 0.88888889],
       [0.30952381, 0.54814815],
       [0.14285714, 0.12592593],
       [0.        , 0.21481481],
       [0.26190476, 0.5037037 ],
       [0.4047619 , 0.05925926],
       [0.21428571, 0.31851852],
       [0.14285714, 0.2962963 ],
       [0.11904762, 0.24444444],
       [0.23809524, 0.47407407],
       [0.0952381 , 0.02222222],
       [0.33333333, 0.75555556],
       [0.21428571, 0.03703704],
       [0.16666667, 0.53333333],
       [0.11904762, 0.37777778],
       [0.33333333, 0.77777778],
       [0.97619048, 0.5037037 ],
       [0.14285714, 0.31851852],
       [0.14285714, 0.02962963],
       [0.11904762, 0.4962963 ],
       [0.0952381 , 0.35555556],
       [0.30952381, 0.39259259],
       [0.16666667, 0.48148148],
       [0.14285714, 0.08888889],
       [0.04761905, 0.05925926],
       [0.35714286, 0.72592593],
       [0.33333333, 0.02222222],
       [0.38095238, 0.71851852],
       [0.        , 0.27407407],
       [0.0952381 , 0.08888889],
       [0.23809524, 0.53333333],
       [0.19047619, 0.01481481],
       [0.28571429, 0.48148148],
       [0.5       , 0.2       ],
       [0.04761905, 0.25185185],
       [0.4047619 , 0.54074074],
       [0.28571429, 0.34814815],
       [0.30952381, 0.76296296],
       [0.14285714, 0.2962963 ],
       [0.23809524, 0.51851852],
       [0.19047619, 0.48888889],
       [0.4047619 , 0.25925926],
       [0.0952381 , 0.48888889],
       [0.28571429, 0.74814815],
       [0.19047619, 0.        ],
       [0.26190476, 0.0962963 ],
       [0.26190476, 0.5037037 ],
       [0.4047619 , 0.21481481],
       [0.4047619 , 0.07407407],
       [0.23809524, 0.8       ],
       [0.4047619 , 0.42962963],
       [0.23809524, 0.16296296],
       [0.21428571, 0.54074074],
       [0.23809524, 0.32592593],
       [0.33333333, 0.52592593],
       [0.35714286, 0.99259259],
       [0.02380952, 0.04444444],
       [0.07142857, 0.42222222],
       [0.19047619, 0.14814815],
       [0.21428571, 0.54814815],
       [0.19047619, 0.52592593],
       [0.47619048, 0.48148148],
       [0.5       , 0.41481481],
       [0.45238095, 0.41481481],
       [0.47619048, 0.34074074],
       [0.45238095, 0.2962963 ],
       [0.57142857, 0.48148148],
       [0.52380952, 0.31111111],
       [0.4047619 , 0.44444444],
       [0.42857143, 0.27407407],
       [0.52380952, 0.32592593],
       [0.54761905, 0.32592593],
       [0.42857143, 0.44444444],
       [0.45238095, 0.42222222],
       [0.52380952, 0.44444444],
       [0.4047619 , 0.28148148],
       [0.54761905, 0.26666667],
       [0.5       , 0.34074074],
       [0.57142857, 0.37037037],
       [0.19047619, 0.12592593],
       [0.28571429, 0.01481481],
       [0.19047619, 0.51111111],
       [0.30952381, 0.31851852],
       [0.35714286, 0.11851852],
       [0.28571429, 0.53333333],
       [0.07142857, 0.39259259],
       [0.23809524, 0.2962963 ],
       [0.11904762, 0.35555556],
       [0.04761905, 0.4962963 ],
       [0.28571429, 0.68148148],
       [0.23809524, 0.32592593],
       [0.02380952, 0.07407407],
       [0.02380952, 0.51851852],
       [0.        , 0.39259259],
       [0.4047619 , 0.32592593],
       [0.28571429, 0.54814815],
       [0.38095238, 0.07407407],
       [0.14285714, 0.54814815],
       [0.21428571, 0.6       ],
       [0.54761905, 0.11111111],
       [0.26190476, 0.34074074],
       [0.04761905, 0.43703704],
       [0.19047619, 0.        ],
       [0.54761905, 0.22222222],
       [0.30952381, 0.45185185],
       [0.42857143, 0.25925926],
       [0.52380952, 0.23703704],
       [0.30952381, 0.        ],
       [0.66666667, 0.32592593],
       [0.26190476, 0.44444444],
       [0.19047619, 0.11111111],
       [0.33333333, 0.88888889],
       [0.33333333, 0.62962963],
       [0.16666667, 0.55555556],
       [0.45238095, 0.13333333],
       [0.4047619 , 0.17037037],
       [0.35714286, 0.4       ],
       [0.        , 0.52592593],
       [0.0952381 , 0.2962963 ],
       [0.4047619 , 0.41481481],
       [0.26190476, 0.98518519],
       [0.26190476, 0.23703704],
       [0.07142857, 0.54074074],
       [0.38095238, 0.74074074],
       [0.19047619, 0.76296296],
       [0.38095238, 0.20740741],
       [0.38095238, 0.42222222],
       [0.11904762, 0.0962963 ],
       [0.4047619 , 0.23703704],
       [0.16666667, 0.05185185],
       [0.14285714, 0.05925926],
       [0.30952381, 0.14074074],
       [0.19047619, 0.00740741],
       [0.30952381, 0.41481481],
       [0.33333333, 0.75555556],
       [0.35714286, 0.20740741],
       [0.35714286, 0.33333333],
       [0.30952381, 0.37777778],
       [0.04761905, 0.4962963 ],
       [0.35714286, 0.19259259],
       [0.4047619 , 0.42222222],
       [0.23809524, 0.12592593],
       [0.14285714, 0.51111111],
       [0.02380952, 0.08148148],
       [0.26190476, 0.20740741],
       [0.02380952, 0.40740741],
       [0.23809524, 0.54814815],
       [0.38095238, 0.20740741],
       [0.28571429, 0.47407407],
       [0.04761905, 0.15555556],
       [0.19047619, 0.48148148],
       [0.4047619 , 0.05185185],
       [0.4047619 , 0.17777778],
       [0.73809524, 0.43703704],
       [0.5       , 0.88148148],
       [0.54761905, 0.41481481],
       [0.95238095, 0.63703704],
       [0.69047619, 0.23703704],
       [0.88095238, 0.85185185],
       [0.80952381, 0.73333333],
       [0.52380952, 0.94074074],
       [0.66666667, 0.05185185],
       [0.71428571, 0.6       ],
       [0.80952381, 1.        ],
       [0.97619048, 0.2       ],
       [0.4047619 , 0.31851852],
       [0.69047619, 0.20740741],
       [1.        , 0.68888889],
       [0.73809524, 0.37037037],
       [0.52380952, 0.46666667],
       [0.66666667, 0.6       ],
       [0.97619048, 0.94814815],
       [0.54761905, 0.48148148],
       [0.4047619 , 0.56296296],
       [0.45238095, 0.95555556],
       [1.        , 0.64444444],
       [0.4047619 , 0.33333333],
       [0.45238095, 0.28148148],
       [0.42857143, 0.82222222],
       [0.9047619 , 0.87407407],
       [0.52380952, 0.42222222],
       [0.57142857, 0.48148148],
       [0.4047619 , 0.97777778],
       [0.5       , 0.2       ],
       [0.52380952, 0.68148148],
       [0.73809524, 0.52592593],
       [0.47619048, 0.71851852],
       [0.66666667, 0.47407407],
       [0.52380952, 0.31111111],
       [0.45238095, 0.48148148],
       [0.66666667, 0.4962963 ],
       [0.83333333, 0.94814815],
       [0.57142857, 0.99259259],
       [0.47619048, 0.32592593],
       [0.76190476, 0.54074074],
       [0.9047619 , 0.65925926],
       [0.54761905, 0.42222222],
       [0.78571429, 0.97037037],
       [0.4047619 , 0.25925926],
       [0.92857143, 0.79259259],
       [0.54761905, 0.27407407],
       [0.4047619 , 0.60740741],
       [0.61904762, 0.17777778],
       [0.45238095, 0.27407407],
       [0.71428571, 0.88148148],
       [0.45238095, 0.97037037],
       [0.76190476, 0.21481481],
       [0.80952381, 0.55555556],
       [0.54761905, 0.42222222],
       [0.52380952, 0.31111111],
       [0.95238095, 0.59259259],
       [0.64285714, 0.85925926],
       [0.4047619 , 0.45925926],
       [0.42857143, 0.95555556],
       [0.88095238, 0.81481481],
       [0.4047619 , 0.42222222],
       [0.71428571, 0.55555556],
       [0.57142857, 0.68888889],
       [0.52380952, 0.44444444],
       [0.45238095, 0.43703704],
       [0.69047619, 0.95555556],
       [0.52380952, 0.34074074],
       [0.5952381 , 0.87407407],
       [0.97619048, 0.45185185],
       [1.        , 0.2       ],
       [0.5       , 0.67407407],
       [0.92857143, 0.08148148],
       [0.92857143, 0.43703704],
       [0.47619048, 0.41481481],
       [0.73809524, 0.54074074],
       [0.80952381, 0.17037037],
       [0.76190476, 0.15555556],
       [0.97619048, 0.54074074],
       [0.4047619 , 0.34074074],
       [0.45238095, 0.40740741],
       [0.80952381, 0.04444444],
       [0.71428571, 0.93333333],
       [0.45238095, 0.57777778],
       [0.45238095, 0.34814815],
       [0.71428571, 0.91111111],
       [0.54761905, 0.47407407],
       [0.45238095, 0.46666667],
       [0.5       , 0.88148148],
       [0.73809524, 0.54814815],
       [0.88095238, 0.17777778],
       [0.45238095, 0.45925926],
       [0.4047619 , 0.31111111],
       [0.42857143, 0.35555556],
       [0.57142857, 0.42962963],
       [0.5952381 , 0.71851852],
       [0.64285714, 0.47407407],
       [0.66666667, 0.75555556],
       [0.95238095, 0.17037037],
       [0.71428571, 0.43703704],
       [0.45238095, 0.9037037 ],
       [0.45238095, 0.47407407],
       [0.52380952, 0.33333333],
       [0.57142857, 0.28888889],
       [0.78571429, 0.88148148],
       [0.69047619, 0.72592593],
       [0.42857143, 0.81481481],
       [0.47619048, 0.25925926],
       [0.57142857, 0.40740741],
       [0.5       , 0.6       ],
       [0.47619048, 0.25925926],
       [0.73809524, 0.93333333],
       [0.5       , 0.47407407],
       [0.5       , 0.44444444],
       [0.85714286, 0.65925926],
       [0.4047619 , 0.2962963 ],
       [0.64285714, 0.12592593],
       [0.42857143, 0.33333333],
       [0.80952381, 0.91111111],
       [0.83333333, 0.4962963 ],
       [0.54761905, 0.27407407],
       [0.71428571, 0.11111111],
       [0.71428571, 0.85925926],
       [0.54761905, 0.33333333],
       [0.54761905, 0.42222222],
       [0.57142857, 0.44444444],
       [0.42857143, 0.76296296],
       [0.69047619, 0.68148148],
       [0.47619048, 0.26666667],
       [0.71428571, 0.77037037],
       [0.57142857, 0.37037037],
       [0.52380952, 0.37037037],
       [0.92857143, 0.33333333],
       [0.42857143, 0.28888889],
       [0.95238095, 0.95555556],
       [0.4047619 , 0.47407407],
       [0.47619048, 0.2962963 ],
       [0.5       , 0.79259259],
       [0.83333333, 0.65925926],
       [0.4047619 , 0.44444444],
       [0.47619048, 0.37037037],
       [0.69047619, 0.26666667],
       [0.69047619, 0.66666667],
       [0.54761905, 0.35555556],
       [0.83333333, 0.42222222],
       [0.85714286, 0.68888889],
       [0.5       , 0.45925926],
       [0.47619048, 0.34074074],
       [0.47619048, 0.72592593],
       [0.45238095, 0.44444444],
       [0.57142857, 0.55555556],
       [0.45238095, 0.31111111],
       [0.42857143, 0.62222222],
       [1.        , 0.14074074],
       [0.85714286, 0.40740741],
       [0.54761905, 0.42222222],
       [0.52380952, 0.41481481],
       [0.57142857, 0.28888889],
       [0.5952381 , 0.84444444],
       [0.83333333, 0.14074074],
       [0.69047619, 0.25925926],
       [0.57142857, 0.47407407],
       [0.57142857, 0.65925926],
       [0.97619048, 0.1037037 ],
       [0.95238095, 0.23703704],
       [0.66666667, 0.54074074],
       [0.47619048, 0.41481481],
       [0.85714286, 0.08148148],
       [1.        , 0.22962963],
       [1.        , 0.5037037 ],
       [0.5       , 0.42962963],
       [0.97619048, 0.85185185],
       [0.45238095, 0.48148148],
       [0.66666667, 0.12592593],
       [0.66666667, 0.43703704],
       [0.57142857, 0.28148148],
       [0.54761905, 0.53333333],
       [0.95238095, 0.05925926],
       [0.57142857, 0.36296296],
       [0.71428571, 0.13333333],
       [0.61904762, 0.91851852],
       [0.73809524, 0.0962963 ],
       [0.92857143, 0.13333333],
       [0.9047619 , 0.33333333],
       [0.73809524, 0.17777778],
       [0.5       , 0.41481481],
       [0.69047619, 0.14074074],
       [0.71428571, 0.14814815],
       [0.71428571, 0.13333333],
       [0.69047619, 0.05925926],
       [0.64285714, 0.22222222],
       [1.        , 0.2       ],
       [0.5       , 0.32592593],
       [0.66666667, 0.19259259],
       [0.78571429, 0.05925926],
       [0.76190476, 0.03703704],
       [0.42857143, 0.13333333],
       [0.73809524, 0.15555556]])

In [ ]:
pd.get_dummies(df1,columns=['Purchased'])

      User ID  Gender  age  EstimatedSalary  Purchased_0  Purchased_1
0    15624510    Male   19            19000         True        False
1    15810944    Male   35            20000         True        False
2    15668575  Female   26            43000         True        False
3    15603246  Female   27            57000         True        False
4    15804002    Male   19            76000         True        False
..        ...     ...  ...              ...          ...          ...
395  15691863  Female   46            41000        False         True
396  15706071    Male   51            23000        False         True
397  15654296  Female   50            20000        False         True
398  15755018    Male   36            33000         True        False
399  15594041  Female   49            36000        False         True

[400 rows x 6 columns]

#**Data Integration**

In [ ]:
df_1 = pd.read_csv('Student_5.csv')
df_2 = pd.read_csv('student3.csv')

In [ ]:
merged_data = pd.merge(df_1, df_2, on='roll')
merged_data

    roll   name_x class_x  marks _x  age_x   name_y class_y  marks _y  age_y
0      1     anil      TE     56.77   22.0     anil      TE     56.77   22.0
1      2     amit      TE     59.77   21.0     amit      TE     59.77   21.0
2      3   aniket      BE     76.88   19.0   aniket      BE     76.88   19.0
3      4  ajinkya      TE     69.66   20.0  ajinkya      TE     69.66   20.0
4      5     asha      TE     63.28    NaN     asha      TE     63.28    NaN
5      6   ayesha      BE       NaN   20.0   ayesha      BE       NaN   20.0
6      7     amar      BE     65.34   19.0     amar      BE     65.34   19.0
7      7     amar      BE     65.34   19.0     amar      BE     65.34   19.0
8      8    Amita      be    168.33   23.0    Amita      be     68.33   23.0
9      9     amol      TE     56.75   20.0     amol      TE     56.75   20.0
10     9     amol      TE     56.75   20.0     amol      TE     56.75   20.0
11    10    anmol      BE     78.66    NaN    anmol      BE     78.66    NaN
12    11   surbhi      TE       NaN   23.0   surbhi      TE       NaN   23.0
13    12    Sujay      TE     74.12   22.0    Sujay      TE     74.12   22.0
14    13  subhash      be     88.45  121.0  subhash      be     88.45   21.0
15    14   sachin     NaN     59.33   21.0   sachin     NaN     59.33   21.0
16    15  shalini      TE     63.45   20.0  shalini      TE     63.45   20.0